CREATE USER c##sonya IDENTIFIED BY Sonya200795 DEFAULT TABLESPACE USERS;

GRANT CREATE SESSION TO c##sonya;
/
GRANT CREATE TABLE TO c##sonya;
/
GRANT CREATE PROCEDURE TO c##sonya;
/
GRANT CREATE TRIGGER TO c##sonya;
/
GRANT CREATE VIEW TO c##sonya;
/
GRANT CREATE SEQUENCE TO c##sonya;
/
GRANT CREATE VIEW TO c##sonya;
/

GRANT DELETE ANY TABLE TO c##sonya;
/
GRANT DROP ANY TABLE TO c##sonya;
/
GRANT DROP ANY PROCEDURE TO c##sonya;
/
GRANT DROP ANY TRIGGER TO c##sonya;
/
GRANT DROP ANY VIEW TO c##sonya;
/

GRANT ALTER ANY TABLE TO c##sonya;
/
GRANT ALTER ANY TABLE TO c##sonya;
/
GRANT ALTER ANY PROCEDURE TO c##sonya;
/
GRANT ALTER ANY TRIGGER TO c##sonya;
/

COMMIT
/

grant insert into table to c##sonya;
COMMIT;